# Site settings
title: 2G GSM Security
email: git@telco-sec.com
description: > # this means to ignore newlines until "baseurl:"
  Explore robust 2G GSM security solutions to fortify your network against potential threats. Our comprehensive security measures ensure the integrity and confidentiality of your 2G GSM communications, providing peace of mind and reliability for your telecommunications infrastructure.
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://2g-gsm.telco-sec.com/" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: rfs

copyright:
   name: TelcoSec
   link: 'https://2g-gsm.telco-sec.com/'


# CDN Images

cdn:
  domain: https://cdn.telco-sec.com/

# Build settings
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: G-SDPPC95R4J

# Comments
disqus: yes
disqus-shortname: poplab

#social
facebook: https://www.facebook.com/PopLabResearch
quora: http://quora.com/
twitter: http://twitter.com/
github: https://github.com/TelcoSec/
email: git@telco-sec.com

#facebook like box
fb-like-box: yes
fb-app-id: xxxxxxxx
fb-page-url: https://www.facebook.com/PopLabResearch
fb-page-title: PopLabResearch

# Sass style
sass:
  style: compressed

# google News
publisher: "PopLab Agency"
# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-news-sitemap

